#!/usr/bin/env bash
# vim: set filetype=sh:

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <launchctl-service-to-disable>"
	exit 1
fi

debug=true

function list {
	if [ -e "$1" ]; then
		echo "==> ls $1"
		ls -1 "$1"
	else
		echo "==> Nothing disabled in $1"
	fi
}

function remove_all {
	service=${1%.plist}
	remove_if_exist "$HOME/Library/LaunchAgents/$service.plist"
	remove_if_exist "/Library/LaunchAgents/$service.plist"
	remove_if_exist "/Library/LaunchDaemons/$service.plist"
	remove_if_exist "/System/LaunchAgents/$service.plist"
	remove_if_exist "/System/LaunchDaemons/$service.plist"
}

function remove_if_exist {
	if [ -e "$1" ]; then
		mkdir_if_not_exist "$(dirname "$1")/Disabled/"
		if [[ $1 == $HOME* ]]; then
			mv -v "$1" "$(dirname "$1")/Disabled/"
		else
			sudo mv -v "$1" "$(dirname "$1")/Disabled/"
		fi
	else
		if [ "$debug" == true ]; then
			echo "$1 does not exist"
		fi
	fi
}

function mkdir_if_not_exist {
	if [ ! -e "$1" ]; then
		if [[ $1 == $HOME* ]]; then
			mkdir -v "$1"
		else
			sudo mkdir -v "$1"
		fi
	fi
}

function disable {
	if [[ $1 == system/* ]]; then
		echo "==> sudo launchctl disable $1"
		sudo launchctl disable "$1"
	else
		echo "==> launchctl disable $1"
		launchctl disable "$1"
	fi
}

function bootout {
	if [[ $1 == system/* ]]; then
		echo "==> sudo launchctl bootout $1"
		sudo launchctl bootout "$1"
	else
		echo "==> launchctl bootout $1"
		launchctl bootout "$1"
	fi
}

if [ "$1" == "-l" ]; then
	list ~/Library/LaunchAgents/Disabled
	list /Library/LaunchAgents/Disabled
	list /Library/LaunchDaemons/Disabled
	list /System/LaunchAgents/Disabled
	list /System/LaunchDaemons/Disabled
else
	bootout "system/$1"
	bootout "user/$UID/$1"
	bootout "gui/$UID/$1"

	# disable
	disable "system/$1"
	disable "user/$UID/$1"
	disable "gui/$UID/$1"

	remove_all "$1"
fi
